# Generated by Django 5.0.3 on 2024-03-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='novel',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='novel_images/'),
        ),
        migrations.AddField(
            model_name='novel',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
