# Generated by Django 5.0.3 on 2024-03-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel_api', '0004_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image_path',
            field=models.ImageField(blank=True, upload_to='novel_images/'),
        ),
    ]
